services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=7x42user
      - DB_PASSWORD=7x42pass
      - DB_NAME=7x42db
      - DB_PORT=5432
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.0-flash-001}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./web:/app/web

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=7x42user
      - POSTGRES_PASSWORD=7x42pass
      - POSTGRES_DB=7x42db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 7x42user -d 7x42db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: